/**
 * suggestionController.js
 *
 * GET   /api/suggestions          Pending suggestions for the authenticated user
 * PATCH /api/suggestions/:id      Accept (records the action) or dismiss
 * POST  /api/suggestions/generate Manually request a fresh batch of AI suggestions
 *
 * Suggestions are generated by Groq using the user's real activity log.
 */

const mongoose = require('mongoose');

const Suggestion = require('../models/Suggestion');
const User = require('../models/User');
const ActivityLog = require('../models/ActivityLog');
const { generateDailySuggestions } = require('../services/AIService');
const { emitUpdate } = require('../services/SocketService');
const { del } = require('../services/RedisService');

const ensureDb = (res) => {
  if (mongoose.connection.readyState !== 1) {
    res.status(503).json({ error: 'Database is currently unavailable. Please retry shortly.' });
    return false;
  }
  return true;
};

const formatSuggestion = (s) => ({
  id: s._id,
  text: s.suggestionText,
  potentialSavingsKg: s.potentialSavingsKg,
  potentialSavingsInr: s.potentialSavingsInr,
  category: s.category,
  status: s.status,
  createdAt: s.createdAt
});

const getSuggestions = async (req, res) => {
  try {
    if (!ensureDb(res)) return;

    let suggestions = await Suggestion.find({ userId: req.userId, status: 'pending' })
      .sort({ createdAt: -1 })
      .limit(10)
      .lean();

    if (suggestions.length === 0) {
      const activityCount = await ActivityLog.countDocuments({ userId: req.userId });
      // Only generate AI suggestions when the user has at least some activity
      // OR when GROQ is configured. Otherwise we return an empty list and let
      // the UI show an honest "Log activity to unlock AI insights" empty state.
      if (process.env.GROQ_API_KEY && activityCount > 0) {
        suggestions = await generateAndSaveSuggestions(req.userId);
      }
    }

    res.json(suggestions.map(formatSuggestion));
  } catch (err) {
    console.error('[suggestionController] getSuggestions error:', err.message);
    res.status(500).json({ error: 'Failed to fetch suggestions' });
  }
};

const actionSuggestion = async (req, res) => {
  try {
    if (!ensureDb(res)) return;
    const { id } = req.params;
    const { action } = req.body;

    if (!['accept', 'dismiss'].includes(action)) {
      return res.status(400).json({ error: 'Action must be accept or dismiss' });
    }

    if (!mongoose.Types.ObjectId.isValid(id)) {
      return res.status(400).json({ error: 'Invalid suggestion id' });
    }

    const suggestion = await Suggestion.findOne({ _id: id, userId: req.userId });
    if (!suggestion) return res.status(404).json({ error: 'Suggestion not found' });
    if (suggestion.status !== 'pending') {
      return res.status(409).json({ error: 'Suggestion has already been actioned' });
    }

    suggestion.status = action === 'accept' ? 'completed' : 'ignored';
    suggestion.actionedAt = new Date();
    await suggestion.save();

    let updatedUser = null;

    if (action === 'accept') {
      const carbonSaved = Math.max(0, Number(suggestion.potentialSavingsKg || 0));
      const rupeesSaved = Math.max(0, Number(suggestion.potentialSavingsInr || 0));

      await ActivityLog.create({
        userId: suggestion.userId,
        category: suggestion.category,
        actionName: `Completed suggestion: ${suggestion.suggestionText.slice(0, 80)}`,
        carbonImpact: -carbonSaved,
        costImpact: -rupeesSaved,
        rawData: { suggestionId: id, source: 'suggestion-accept' }
      });

      const user = await User.findById(suggestion.userId);
      if (user) {
        user.totalCarbonSaved = Number((user.totalCarbonSaved + carbonSaved).toFixed(3));
        user.totalRupeesSaved = Number((user.totalRupeesSaved + rupeesSaved).toFixed(2));

        const today = new Date().toDateString();
        const last = user.lastActiveDate ? new Date(user.lastActiveDate).toDateString() : null;
        const yesterday = new Date(Date.now() - 86400000).toDateString();
        if (last !== today) {
          user.currentStreak = last === yesterday ? (user.currentStreak || 0) + 1 : 1;
          user.lastActiveDate = new Date();
        }

        user.recalculateEcoScore();
        await user.save();

        updatedUser = {
          id: user._id,
          name: user.name,
          ecoScore: user.ecoScore,
          currentStreak: user.currentStreak,
          totalCarbonSaved: user.totalCarbonSaved,
          totalRupeesSaved: user.totalRupeesSaved,
          ecoPoints: user.ecoPoints
        };

        emitUpdate(user._id.toString(), updatedUser);
        await del('leaderboard:global');
        await del('stats:global');
      }
    }

    res.json({ success: true, id, action, status: suggestion.status, updatedUser });
  } catch (err) {
    console.error('[suggestionController] actionSuggestion error:', err.message);
    res.status(500).json({ error: 'Failed to update suggestion' });
  }
};

const generateSuggestions = async (req, res) => {
  try {
    if (!ensureDb(res)) return;
    if (!process.env.GROQ_API_KEY) {
      return res.status(503).json({ error: 'AI suggestions are not configured on this server.' });
    }
    const suggestions = await generateAndSaveSuggestions(req.userId);
    res.json({
      success: true,
      count: suggestions.length,
      suggestions: suggestions.map(formatSuggestion)
    });
  } catch (err) {
    console.error('[suggestionController] generateSuggestions error:', err.message);
    res.status(500).json({ error: err.message || 'Failed to generate suggestions' });
  }
};

const generateAndSaveSuggestions = async (userId) => {
  const user = await User.findById(userId).lean();
  if (!user) throw new Error('User not found');

  const sevenDaysAgo = new Date(Date.now() - 7 * 24 * 3600 * 1000);
  const activityLogs = await ActivityLog.find({
    userId,
    timestamp: { $gte: sevenDaysAgo }
  })
    .sort({ timestamp: -1 })
    .limit(20)
    .lean();

  const aiSuggestions = await generateDailySuggestions(user, activityLogs);

  const saved = await Suggestion.insertMany(
    aiSuggestions.map((s) => ({
      userId,
      suggestionText: s.suggestionText,
      potentialSavingsKg: Math.max(0, Number(s.potentialSavingsKg) || 0),
      potentialSavingsInr: Math.max(0, Number(s.potentialSavingsInr) || 0),
      category: ['Browser', 'Hardware', 'Lifestyle'].includes(s.category) ? s.category : 'Browser',
      status: 'pending'
    }))
  );

  return saved;
};

module.exports = { getSuggestions, actionSuggestion, generateSuggestions };
